# Generated by Django 5.1.5 on 2025-01-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aks', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
